### ISSUE TITLE
Zizmor findings, release-pls considerations?

### ISSUE THREAD

**Issue by cpu** [rustls/ktls#51]
:wave: I've been running [zizmor](https://woodruffw.github.io/zizmor/) across the varios Rustls org repos this morning and wanted to share some findings for `ktls`.

I've been fixing them myself in other repos, but had some pause doing the same here because they're all related to the `release-plz` workflow and it's both a tool I'm unfamiliar with and one I suspect is hard to test in a dry-run capacity. I wouldn't want to break the process making what feels like a small no-op change only to discover down the road it hosed your release process.

<details>
<summary>Here are the findings. Nothing that's an immediate emergency, but perhaps still worth fixing:</summary>

```
[daniel@noire:~/Code/Rust/ktls]$ ~/.cargo/bin/zizmor .github/workflows/
🌈 completed release-plz.yaml
🌈 completed test.yml
warning[artipacked]: credential persistence through GitHub Actions artifacts
  --> /home/daniel/Code/Rust/ktls/.github/workflows/release-plz.yaml:16:9
   |
16 |         - name: Checkout repository
   |  _________-
17 | |         uses: actions/checkout@v4
18 | |         with:
19 | |           fetch-depth: 0
   | |________________________- does not set persist-credentials: false
   |
   = note: audit confidence → Low

error[excessive-permissions]: overly broad workflow or job-level permissions
 --> /home/daniel/Code/Rust/ktls/.github/workflows/release-plz.yaml:3:1
  |
3 | / permissions:
4 | |   pull-requests: write
5 | |   contents: write
  | |_________________^ pull-requests: write is overly broad at the workflow level
  |
  = note: audit confidence → High

error[excessive-permissions]: overly broad workflow or job-level permissions
 --> /home/daniel/Code/Rust/ktls/.github/workflows/release-plz.yaml:3:1
  |
3 | / permissions:
4 | |   pull-requests: write
5 | |   contents: write
  | |_________________^ contents: write is overly broad at the workflow level
  |
  = note: audit confidence → High

warning[artipacked]: credential persistence through GitHub Actions artifacts
  --> /home/daniel/Code/Rust/ktls/.github/workflows/test.yml:18:9
   |
18 |         - name: Check out repository code
   |  _________-
19 | |         uses: actions/checkout@v4
   | |_________________________________- does not set persist-credentials: false
   |
   = note: audit confidence → Low

warning[ref-confusion]: git ref for action with ambiguous ref type
  --> /home/daniel/Code/Rust/ktls/.github/workflows/test.yml:26:9
   |
26 |       - uses: taiki-e/install-action@v2
   |         ------------------------------- uses a ref that's provided by both the branch and tag namespaces
   |
   = note: audit confidence → High

10 findings (5 suppressed): 0 unknown, 0 informational, 0 low, 3 medium, 2 high
```
</details>

FWIW In the other Rustls crates we're choosing to not fix the `ref-confusion` findings by switching to SHA pins since the ergonomics are fairly poor and we have tried hard to almost never give interesting permissions (such as `write`) to our CI jobs, instead preferring boring CI and manual releases. We have been fixing findings related to minimizing workflow-level permissions, and using `persist-credentials: false` ubiquitously.

Outside of Zizmor findings, how do you feel about the risk/reward calculus for using `release-plz` with this crate? In [this discussion thread](https://github.com/rustls/rustls/pull/2261#pullrequestreview-2485638753) both myself and Ctz expressed a general distrust of automated crate publishing from GitHub actions, but that was before I noticed this repo was doing that :-) AFAIK it's the only crate in the org that does so.

**Comment by cpu** [comment]
_(Edited to remove the now revoked GH_TOKEN I pasted in the output by mistake :man_facepalming: )_

**Comment by djc** [comment]
I think https://github.com/rust-lang/rfcs/pull/3691 is the way forward.

**Comment by cpu** [comment]
cc @MarcoIeni for visibility. 

This is more about aligning release practices across our organization than any particular fault with your tool, but you may be interested in the findings Zizmor spits out in case it could be helpful for [upstream docs](https://release-plz.dev/docs/github). Given the sensitive nature of security libraries deep in the dep. tree we're perhaps more conservative about this sort of thing than other projects might be :bow:

**Comment by MarcoIeni** [comment]
Hi! Thanks for all the feedback!

I'll answer partially because I'm from my phone. 

To answer to Amos, I work at the foundation but I work on release-plz in my spare time. At the foundation I work in the infra team 👍

`contents: write` is needed to publish github releases, push tags and similar.

Also, isn't the rfc linked orthogonal to release-plz? 
Release-plz will publish tags, make changelog, check semver, puglish github releases. While that rfc only changes how cargo publish works, right? (maybe I'm missing something). 

Anyway, if you have ideas on how to make release-plz more secure, PRs or issues are welcome 👍👍

**Comment by MarcoIeni** [comment]
Hey, I had some time to look into this.

Fixing the findings of zizmor for the release-plz workflow is quite easy:
![image](https://github.com/user-attachments/assets/69128304-8008-4c67-a2b8-0192400389e3)

Probably I'll edit the docs of the action to move the `permissions` to the jobs 👍

Of course release-plz needs high privileges to run `cargo publish`, push git tags, open PRs, etc.
If you feel safer to publish from your laptop, I get that! Probably you are using 2FA to login to crates.io and you know what you are doing. 👍

Maybe you can consider running `release-plz update`, `release-plz release-pr` or `release-plz release` locally to speed up your release process :)

> plans to make release-plz work in more “locked down” scenarios

I don't have good ideas about this. Of course you can run `cargo publish` by yourself and use release-plz just for the release PR, but the GitHub Action requires `contents: write` unfortunately :(

Anyway thank you for looping me in in the conversation and for your fantastic work on rustls 🙏
